### ISSUE TITLE
Traceback Error 

### ISSUE THREAD

**Issue by B3voholic** [brianpeiris/switchmate#11]
Hello, I'm trying to get my switchmate working and I keep getting the following error.  I was wondering if anyone had any tips.  The error is following.

```
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/shell/switchmate.py", line 283, in <module>
    mac_address = arguments['<mac_address>']
KeyError: '<mac_address>'
```

Any help is appreciated.

**Comment by brianpeiris** [comment]
I'm not familiar with homeassistant, so I'm not sure what it's trying to do here. When do you receive the error?

**Comment by B3voholic** [comment]
I'm trying to flip the switch using the command line and it's giving that error.  I'm running this command ```sudo /home/homeassistant/.homeassistant/shell/switchmate.py XX:XX:XX:XX:XX:XX none switch on``` and it's giving me that message.  I have copied your switchmate.py exactly.

**Comment by brianpeiris** [comment]
I'm afraid I'll never get around to setting up Home Assistant and trying this myself. @B3voholic Let me know if you still care about this issue, or if I should just close it.

Of course, if someone else wants to help out, please do!

**Comment by rotcop4u2** [comment]
you probably have to execute the command the same way you would in the terminal.. sudo python3 /home/homeassistant/.homeassistant/shell/switchmate.py XX:XX:XX:XX:XX:XX switch on
