### ISSUE TITLE
bluepy, docopt and other dependencies on HA Linux Image

### ISSUE THREAD

**Issue by rotcop4u2** [brianpeiris/switchmate#12]
Hello,

I'm trying to use your script but am unable to get the dependencies. do you know where to locate them?

**Comment by brianpeiris** [comment]
switchmate uses the typical method for python dependencies. They are specified in the [`requirements.txt`](https://github.com/brianpeiris/switchmate/blob/master/requirements.txt) file and can be installed with pip: `pip install -r requirements.txt`

**Comment by rotcop4u2** [comment]
I'm having some issues trying to run the ./switchmate.py scan command.. it
says permission denied even when I run in sudo su

**Comment by brianpeiris** [comment]
Can you paste the full error?

**Comment by rotcop4u2** [comment]
master# bash switchmate.py scan
switchmate.py: line 36: switchmate.py

A python-based command line utility for controlling Switchmate switches.

Usage:
    ./switchmate.py scan [options]
    ./switchmate.py status [options]
    ./switchmate.py <mac_address> status [options]
    ./switchmate.py <mac_address> switch (on | off)
    ./switchmate.py <mac_address> toggle
    ./switchmate.py <mac_address> battery-level
    ./switchmate.py <mac_address> debug
    ./switchmate.py (-h | --help) | help

Commands:
    scan
        Scan for switchmate devices and print their mac addresses.
    status
        Scan for switchmate devices and print their mac addresses and status.
    switch (on | off)
        Switch a device on or off.
    toggle
        Switch a device on if currently off, or off if currently on.
    debug
        Print a detailed information about a device, for debugging purposes.
    help
        Show this help screen.

Options:
    -t <seconds>, --timeout=<seconds>  [default: 2]
        Search for devices until this timeout.
    -h, --help
        Show this help screen.
: No such file or directory
from: can't read /var/mail/__future__
switchmate.py: line 39: import: command not found
from: can't read /var/mail/docopt
switchmate.py: line 42: syntax error near unexpected token `('
switchmate.py: line 42: `from bluepy.btle import ('
root@HOMEASSISTANT:/home/homeassistant/.homeassistant/python_scripts/switchmate-                                                                                        master# cd ..
root@HOMEASSISTANT:/home/homeassistant/.homeassistant/python_scripts# python swi                                                                                        tchmate.py scan
Traceback (most recent call last):
  File "switchmate.py", line 41, in <module>
    from docopt import docopt
ImportError: No module named docopt

**Comment by rotcop4u2** [comment]
i pip3 install -r requirements.txt already and it grabbed all the dependencies

**Comment by brianpeiris** [comment]
Might be easier if we chat in realtime on Gitter: https://gitter.im/brianpeiris-switchmate/Lobby

**Comment by brianpeiris** [comment]
Turns out @rotcop4u2 was running HomeAssistant's flavor of Linux on a Raspberry Pi 3B+

We got things partially working with these commands:

```
$ pip3 install -r requirements.txt
$ sudo pip3 install bluepy
$ pushd /usr/local/lib/python3.5/dist-packages/bluepy/
$ sudo make
$ popd
$ sudo python3 ./switchmate.py scan
```

But there is still an issue with finding particular switches.

**Comment by lawrence-jeff** [comment]
> But there is still an issue with finding particular switches.

Are you having issues with the code seeing some devices -in my cases the code scans and if I add debug statements listing the macs it sees it sees the switchmate devices but skips past them as they don't match the service id in the code - are you seeing this also?

**Comment by brianpeiris** [comment]
@rotcop4u2 Let me know if this is still an issue for you with the new fix or if I can close this issue.

**Comment by brianpeiris** [comment]
I'm going to close this for now. Feel free to reopen if you need to.
