### ISSUE TITLE
Windows compatibility 

### ISSUE THREAD

**Issue by takuy** [brianpeiris/switchmate#17]
I'm very interested in getting this to work on Windows. Currently, Bluepy doesn't work on Windows (and there's no plan for it to work). Maybe something like https://github.com/pybluez/pybluez would work. I'll try it change it over in my spare time.

It'd be a great feature otherwise.

**Comment by takuy** [comment]
Turns out Pybluez has no support for BLE on Windows, and Switchmates function over BLE. Oh well.

**Comment by brianpeiris** [comment]
Looks like this supports Windows 10 BLE: https://github.com/TheCellule/python-bleson

**Comment by brianpeiris** [comment]
Also https://github.com/hbldh/bleak

**Comment by takuy** [comment]
Yeah - I started to look into Bleak and Bleson late last night. I'll see what I can whip up.

**Comment by brianpeiris** [comment]
Gonna close this for now. Feel free to reopen if you have an update.
