### ISSUE TITLE
Dependency fails on MacOS

### ISSUE THREAD

**Issue by thevickypedia** [brianpeiris/switchmate#20]
Unable to install the dependency `bluepy`

```
fatal error: 'byteswap.h' file not found
#include` <byteswap.h>
1 error generated.
make: *** [bluepy-helper] Error 1"
  ----------------------------------------
  ERROR: Failed building wheel for bluepy
```

I've also raised an [issue](https://github.com/IanHarvey/bluepy/issues/194#issuecomment-733696079) with `bluepy` but is there any way around to get `switchmate` working on my Mac?

**Comment by brianpeiris** [comment]
I'm afraid I can't help with bluepy issues, and this library requires bluepy to work. I'd suggest trying a linux machine instead, like a raspberry PI.

**Comment by brianpeiris** [comment]
You might also want to try this node.js based project instead, though I'm not sure if it's in a working condition https://github.com/valkjsaaa/node-switchmate3
